[project]
name = '100daysofclarity'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'
requirements = []
[contracts.clarity-basics-i]
path = 'contracts/clarity-basics-i.clar'
clarity_version = 1
epoch = 2.0

[contracts.clarity-basics-ii]
path = 'contracts/clarity-basics-ii.clar'
clarity_version = 1
epoch = 2.0

[contracts.community-hello-world]
path = 'contracts/community-hello-world.clar'
clarity_version = 1
epoch = 2.0
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
