[project]
name = '100daysofclarity'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'
requirements = []
[contracts.artist-discography]
path = 'contracts/artist-discography.clar'
clarity_version = 1
epoch = 2.0

[contracts.clarity-basics-i]
path = 'contracts/clarity-basics-i.clar'
clarity_version = 1
epoch = 2.0

[contracts.clarity-basics-ii]
path = 'contracts/clarity-basics-ii.clar'
clarity_version = 1
epoch = 2.0

[contracts.clarity-basics-iii]
path = 'contracts/clarity-basics-iii.clar'
clarity_version = 1
epoch = 2.0

[contracts.clarity-basics-iv]
path = 'contracts/clarity-basics-iv.clar'
clarity_version = 1
epoch = 2.0

[contracts.clarity-basics-v]
path = 'contracts/clarity-basics-v.clar'
clarity_version = 1
epoch = 2.0

[contracts.clarity-basics-vi]
path = 'contracts/clarity-basics-vi.clar'
clarity_version = 1
epoch = 2.0

[contracts.community-hello-world]
path = 'contracts/community-hello-world.clar'
clarity_version = 1
epoch = 2.0

[contracts.ft-simple]
path = 'contracts/ft-simple.clar'
clarity_version = 1
epoch = 2.0

[contracts.marketplace]
path = 'contracts/marketplace.clar'
clarity_version = 1
epoch = 2.0

[contracts.nft-advanced]
path = 'contracts/nft-advanced.clar'
clarity_version = 1
epoch = 2.0

[contracts.nft-simple]
path = 'contracts/nft-simple.clar'
clarity_version = 1
epoch = 2.0

[contracts.odds-and-events]
path = 'contracts/odds-and-events.clar'
clarity_version = 1
epoch = 2.0

[contracts.offspring-will]
path = 'contracts/offspring-will.clar'
clarity_version = 1
epoch = 2.0

[contracts.sip-09]
path = 'contracts/sip-09.clar'
clarity_version = 1
epoch = 2.0

[contracts.sip-10]
path = 'contracts/sip-10.clar'
clarity_version = 1
epoch = 2.0

[contracts.staking-simple]
path = 'contracts/staking-simple.clar'
clarity_version = 1
epoch = 2.0
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
